platform :ios, '8.1'
pod 'AFNetworking', '~>2.4.1'
pod 'JSONModel', '~> 1.0.1'
pod 'Masonry','~>0.6.0'
pod 'FMDB/common' , '~>2.5'
pod 'FMDB/SQLCipher', '~>2.5'
pod 'SDWebImage', '~>3.6'
pod 'Qiniu','~> 7.0'
pod 'SVProgressHUD'